java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    aac:
      secrets:
        - aac-manage-case-s2s-secret
        - aac-manage-case-datastore-proxy-url-whitelist
        - idam-mca-client-secret
        - idam-mca-system-user-username
        - idam-mca-system-user-password
  environment:
    S2S_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
